#!/bin/bash

SCRIPT_NAME="$0"
ARGS="$@"
NEW_FILE="/tmp/$0"
VERSION="0.1.5"

update () {
    echo "Checking for updates..."
    echo
    
    # download most recent version
    rm -f "$NEW_FILE"
    wget -P /tmp "https://raw.githubusercontent.com/MrGallo/bash-scripts/master/$0" && {
        echo "Download complete"
        
        NF_V=$(head -6 $NEW_FILE | tail -1)
        NF_V="${NF_V//[^0-9]/}"
        
        if [ "${VERSION//[^0-9]/}" != "$NF_V" ]; then 
            echo "Versions different."
            echo "Updating current version."
            cp "$NEW_FILE" "$SCRIPT_NAME"
            rm -f "$NEW_FILE"
            
            echo "run the new script (in theory)"
            # $SCRIPT_NAME $ARGS
            
            exit 0
        else
            echo "Current version up to date."
            rm -f "$NEW_FILE"
        fi
    }

    
}

main () {
    echo "$0 v$VERSION"
    echo
    if [ ! $ARGS ]; then
        echo "Usage:"
        echo "$0 start - Starts a test session"
        echo "$0 end   - Ends a test session"
        echo
        exit 0
    fi
}

update
main
